(()=>{"use strict";const c=document.getElementById("game"),x=c.getContext("2d"),W=c.width,H=c.height,G=610;const hp=document.getElementById("hp"),sc=document.getElementById("score"),sp=document.getElementById("specialText"),sf=document.getElementById("specialFill"),dif=document.getElementById("difficultyOverlay"),hint=document.getElementById("loadingHint"),ov=document.getElementById("overlay"),fs=document.getElementById("finalScore");
const D={easy:{hp:8,s:.8,p:1.3,g:20,i:1500},normal:{hp:5,s:1,p:1,g:14,i:1200},hard:{hp:3,s:1.22,p:.78,g:10,i:900}},L={1:{y:555,b:625},2:{y:365,b:455},3:{y:265,b:350},4:{y:170,b:255}};
const F={neutral:"neutral.webp",midStart:"high_kick_start.webp",midHit:"mid_kick_hit.webp",lowStart:"low_kick_start.webp",lowHit:"low_kick_hit.webp",highStart:"mid_kick_start.webp",highHit:"high_kick_hit.webp",jump:"jump.webp",jumpAttackStart:"jump_attack_start.webp",jumpAttackHit:"jump_attack_hit.webp",landing:"landing.webp"},I={};let rd=0;for(const[k,f]of Object.entries(F)){const im=new Image();im.onload=()=>rd++;im.onerror=()=>rd++;im.src=f;I[k]=im}
let S={started:false,running:false,enemies:[],parts:[],difficulty:D.normal,difficultyName:"normal",score:0,hp:5,special:0,elapsed:0,facing:1,player:{x:W/2,y:G,vy:0,grounded:true,action:"neutral",t:0,serial:0,inv:0,magic:0}},inp={};
function hud(){hp.textContent=S.hp;sc.textContent=S.score;sp.textContent=Math.floor(S.special)+"%";sf.style.width=S.special+"%"}function reset(n){const d=D[n];S={started:true,running:true,enemies:[],parts:[],difficulty:d,difficultyName:n,score:0,hp:d.hp,special:0,elapsed:0,spawn:2200,grace:3000,facing:1,player:{x:W/2,y:G,vy:0,grounded:true,action:"neutral",t:0,serial:0,inv:0,magic:0}};dif.classList.add("hidden");ov.classList.add("hidden");hud()}
document.querySelectorAll("[data-difficulty]").forEach(b=>b.onclick=()=>reset(b.dataset.difficulty));document.getElementById("restart").onclick=()=>reset(S.difficultyName);
function press(k){if(!S.running)return;const p=S.player;if(k==="left")S.facing=-1;if(k==="right")S.facing=1;if(k==="jump"&&p.grounded){p.grounded=false;p.vy=inp.up?-1080:-860;p.action="jump";p.t=0}else if(k==="attack"){if(!p.grounded){p.action="jumpAttack";p.t=0;p.serial++}else if(p.action==="neutral"){p.action=inp.up?"high":inp.down?"low":"mid";p.t=0;p.serial++}}else if(k==="special"&&S.special>=100){S.special=0;p.magic=4200;p.action="special";p.t=0;burst(W/2,H/2,35);hud()}}
document.querySelectorAll("[data-input]").forEach(b=>{const k=b.dataset.input;b.onpointerdown=e=>{e.preventDefault();if(!inp[k])press(k);inp[k]=1};b.onpointerup=b.onpointercancel=b.onpointerleave=e=>{inp[k]=0}});
function spawn(){const side=Math.random()<.5?-1:1,r=Math.random();let e;if(r<.2)e={t:"strawberry",h:1,v:115,q:120,col:"#ff477e"};else if(r<.4)e={t:"melon",h:1,v:92,q:145,col:"#9fe870",bounce:1,min:1,max:2,ph:Math.random()*6.28};else if(r<.6)e={t:"grape",h:2,v:102,q:155,col:"#9a5de2"};else if(r<.77)e={t:"lemon",h:2,v:112,q:165,col:"#ffd84b"};else if(r<.92)e={t:"pineapple",h:3,v:108,q:190,col:"#ffb739"};else e={t:"watermelon",h:4,v:103,q:240,col:"#56c96f"};e.v*=S.difficulty.s;const l=L[e.h];S.enemies.push({...e,side,x:side<0?-90:W+90,y:l.b,hy:l.y,dead:0,last:-1})}
function burst(a,b,n){for(let i=0;i<n;i++)S.parts.push({x:a,y:b,vx:(Math.random()-.5)*450,vy:-Math.random()*380,life:500+Math.random()*600,size:3+Math.random()*7,h:Math.random()*360})}
function ah(){const a=S.player.action;return a==="low"?1:a==="mid"?2:a==="high"?3:a==="jumpAttack"?4:0}function active(){const p=S.player;return["low","mid","high"].includes(p.action)?p.t>110&&p.t<250:p.action==="jumpAttack"?p.t>80&&p.t<320:false}
function defeat(e,g){if(e.dead)return;e.dead=1;S.score+=e.q;if(g)S.special=Math.min(100,S.special+S.difficulty.g);burst(e.x,e.y-50,12);hud()}
function update(dt){if(!S.running)return;S.elapsed+=dt;S.grace=Math.max(0,(S.grace||0)-dt);const p=S.player;p.t+=dt;p.inv=Math.max(0,p.inv-dt);if(!p.grounded){p.vy+=2150*dt/1000;p.y+=p.vy*dt/1000;if(p.y>=G){p.y=G;p.vy=0;p.grounded=1;p.action="landing";p.t=0}}if(["low","mid","high"].includes(p.action)&&p.t>390){p.action="neutral";p.t=0}if(p.action==="landing"&&p.t>170){p.action="neutral";p.t=0}if(p.magic>0){p.magic-=dt;p.action="special";if(p.t>250){for(const e of S.enemies)if(!e.dead)defeat(e,false);if(Math.random()<.45)burst(W/2,H/2,4)}if(p.magic<=0){p.action="neutral";p.t=0}}
if(active()){const h=ah(),yy=L[h].y;let n=0;for(const e of S.enemies){if(e.dead||e.side!==S.facing||e.last===p.serial)continue;if(Math.abs(e.x-p.x)<=(p.action==="jumpAttack"?335:285)&&Math.abs(e.hy-yy)<75){e.last=p.serial;defeat(e,true);if(++n>=(p.action==="jumpAttack"?4:2))break}}}
S.spawn-=dt;if(S.spawn<=0){spawn();S.spawn=(Math.max(700,1350-S.elapsed*.010)+Math.random()*480)*S.difficulty.p}
for(const e of S.enemies){if(e.dead)continue;if(e.bounce){e.ph+=.0038*dt;const w=(Math.sin(e.ph)+1)/2,a=L[e.min],b=L[e.max];e.hy=a.y+(b.y-a.y)*w;e.y=a.b+(b.b-a.b)*w;e.h=w<.5?1:2}e.x+=-e.side*e.v*dt/1000;if(Math.abs(e.x-p.x)<48){if(p.magic>0)defeat(e,false);else if((S.grace||0)<=0&&p.inv<=0){p.inv=S.difficulty.i;S.hp--;e.dead=1;burst(p.x,p.y-100,14);hud();if(S.hp<=0){S.running=0;fs.textContent="SCORE "+S.score;ov.classList.remove("hidden")}}}}
S.enemies=S.enemies.filter(e=>!e.dead&&e.x>-180&&e.x<W+180);for(const q of S.parts){q.life-=dt;q.vy+=650*dt/1000;q.x+=q.vx*dt/1000;q.y+=q.vy*dt/1000}S.parts=S.parts.filter(q=>q.life>0)}
function bg(){const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,"#94e1ff");g.addColorStop(.58,"#eefcff");g.addColorStop(.59,"#a4e77e");g.addColorStop(1,"#4eb96c");x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle="#fff9";for(let i=0;i<7;i++){x.beginPath();x.arc(120+i*190,120+(i%2)*45,55,0,6.28);x.fill()}x.fillStyle="#c9a9ff";x.fillRect(540,170,200,240)}
function enemy(e){x.save();x.translate(e.x,e.y);x.scale(e.side*.88,.88);x.fillStyle=e.col;x.strokeStyle="#53305c88";x.lineWidth=5;if(e.t==="strawberry"){x.beginPath();x.arc(0,-48,34,0,6.28);x.fill();x.stroke()}else if(e.t==="melon"||e.t==="watermelon"){x.beginPath();x.arc(0,-48,e.t==="melon"?40:44,0,6.28);x.fill();x.stroke()}else if(e.t==="grape"){for(let r=0;r<3;r++)for(let c=0;c<3-r;c++){x.beginPath();x.arc((c-(2-r)/2)*26,-90+r*26,16,0,6.28);x.fill();x.stroke()}}else if(e.t==="lemon"){x.beginPath();x.ellipse(0,-52,44,30,0,0,6.28);x.fill();x.stroke()}else{x.beginPath();x.ellipse(0,-55,40,48,0,0,6.28);x.fill();x.stroke()}x.fillStyle="#3a244d";x.beginPath();x.arc(-13,-55,6,0,6.28);x.arc(13,-55,6,0,6.28);x.fill();x.restore()}
function pim(){const p=S.player;if(p.action==="jump")return I.jump;if(p.action==="jumpAttack")return p.t<120?I.jumpAttackStart:I.jumpAttackHit;if(p.action==="landing")return I.landing;if(p.action==="low")return p.t<120||p.t>260?I.lowStart:I.lowHit;if(p.action==="mid")return p.t<105||p.t>250?I.midStart:I.midHit;if(p.action==="high")return p.t<150||p.t>295?I.highStart:I.highHit;return I.neutral}
function draw(){bg();for(const e of S.enemies)enemy(e);const p=S.player,im=pim();x.save();x.translate(p.x,p.y);x.scale(S.facing,1);if(p.inv>0&&Math.floor(p.inv/80)%2===0)x.globalAlpha=.35;if(im&&im.complete&&im.naturalWidth)x.drawImage(im,-170,-310,340,340);x.restore();for(const q of S.parts){x.fillStyle=`hsl(${q.h} 90% 65%)`;x.beginPath();x.arc(q.x,q.y,q.size,0,6.28);x.fill()}if((S.grace||0)>0){x.fillStyle="rgba(255,255,255,.88)";x.font="900 46px sans-serif";x.textAlign="center";x.fillText("READY!",W/2,95)}if(p.magic>0){x.fillStyle="#fff9";x.fillRect(0,0,W,H);x.fillStyle="#8d42d8";x.font="900 52px sans-serif";x.textAlign="center";x.fillText("RAINBOW MAGIC!",W/2,90)}hint.textContent=rd<11?`キャラクターを読み込み中 ${rd}/11`:"準備完了"}
let last=performance.now();function loop(n){const dt=Math.min(34,n-last);last=n;if(S.started)update(dt);draw();requestAnimationFrame(loop)}hud();requestAnimationFrame(loop)})();